namespace iPhotos.Application.Abstractions;

/// <summary>Which derived variant an ML job consumes.</summary>
public enum MlInputKind
{
    Preview,
    Thumbnail,
}

/// <summary>
/// Local handoff cache for ML job inputs (doc 18 §6.2): the pipeline that generates
/// the preview/thumbnail variants saves the freshly generated bytes here, so the
/// faces/labels workers consume them from disk instead of re-downloading the blobs.
/// Best-effort by contract — implementations never throw; every miss falls back to
/// blob storage at the call site.
/// </summary>
public interface IMlInputCache
{
    /// <summary>Stores the content as the cached input file (overwrites any previous
    /// bytes). Does not dispose the stream; reads from position 0 and rewinds the
    /// stream afterwards, so the caller can hand it straight to blob storage.</summary>
    Task SaveAsync(Guid photoId, MlInputKind kind, Stream content, CancellationToken cancellationToken = default);

    /// <summary>Opens the cached input seekable at position 0, or null on a miss.</summary>
    Task<Stream?> TryOpenReadAsync(Guid photoId, MlInputKind kind, CancellationToken cancellationToken = default);

    /// <summary>Drops the cached input after its last consumer succeeded.</summary>
    void Delete(Guid photoId, MlInputKind kind);

    /// <summary>Hygiene sweep: deletes cached inputs older than maxAge (orphans of
    /// deleted photos, jobs lost to restarts, early-complete paths).</summary>
    Task DeleteStaleAsync(TimeSpan maxAge, CancellationToken cancellationToken = default);
}
